import { makeStyles } from "@mui/styles";

export default makeStyles(({ functions }) => {
  const { pxToRem } = functions;
  return {
    title_table_row_style: {
      display: "flex",
      justifyContent: "space-between",
      width: "100%",
      textAlign: "center",
      padding: "0 1rem",
      backgroundColor: "#f5f5f5",
    },
    table_row_style: {
      display: "flex",
      justifyContent: "space-between",
      width: "100%",
      cursor: "pointer",
      textAlign: "center",
      padding: "0 1rem",
      transition: "background-color 0.1s ease",
      "&:hover": {
        backgroundColor: "#f5f5f5",
      },
    },
    line_form_style: {
      display: "flex",
      alignItems: "center",
      marginBottom: "14px",
      color: "#000000",
      fontSize: "18px",
    },
    columns_center: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
    },
    title_request_name: {
      width: pxToRem(120),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_module: {
      width: pxToRem(120),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_driver: {
      width: pxToRem(300),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_detail: {
      width: pxToRem(300),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_release_date: {
      width: pxToRem(120),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_vaildation_duration: {
      width: pxToRem(300),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_status: {
      width: pxToRem(120),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_action: {
      width: pxToRem(200),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    request_name: {
      width: pxToRem(120),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(12),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    module: {
      width: pxToRem(120),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(12),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    driver: {
      width: pxToRem(300),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(12),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    detail: {
      width: pxToRem(300),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(12),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    release_date: {
      width: pxToRem(120),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(12),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    vaildation_duration: {
      width: pxToRem(300),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(12),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    status: {
      width: pxToRem(120),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(12),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    action: {
      width: pxToRem(200),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(12),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    signin: {
      width: pxToRem(200),
      display: "flex",
      alignItems: "center",
      justifyContent: "flex-start",
      fontSize: pxToRem(12),
      wordWrap: "break-word",
      borderBottom: "none !important",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
  };
});
