import { makeStyles } from "@mui/styles";

export default makeStyles(({ functions }) => {
  const { pxToRem } = functions;
  return {
    title_table_row_style: {
      display: "flex",
      justifyContent: "space-between",
      width: "100%",
      textAlign: "center",
      // border: "1px solid black",
      padding: "0 1rem",
      backgroundColor: "#E6C786",
    },
    table_row_style: {
      display: "flex",
      justifyContent: "space-between",
      width: "100%",
      textAlign: "center",
      padding: "0 1rem",
      transition: "background-color 0.1s ease",
      "&:hover": {
        backgroundColor: "#f5f5f5",
      },
    },
    borderedOptionStyle: {
      border: "1px solid #000",
      padding: "3px",
      margin: "4px",
      maxWidth: "500px",
    },
    containerStyle: {
      display: "flex",
    },
    line_form_style: {
      display: "flex",
      alignItems: "center",
      marginBottom: "14px",
      color: "#000000",
      fontSize: "18px",
    },
    title_platform_style: {
      width: pxToRem(150),
      textAlign: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_phase_style: {
      width: pxToRem(90),
      textAlign: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_target_style: {
      width: pxToRem(90),
      textAlign: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_group_style: {
      width: pxToRem(130),
      textAlign: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_cycle_style: {
      width: pxToRem(90),
      textAlign: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_sku_style: {
      width: pxToRem(70),
      textAlign: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_sn_style: {
      width: pxToRem(150),
      textAlign: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_borrower_style: {
      width: pxToRem(100),
      textAlign: "center",
      fontSize: pxToRem(16),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_status_style: {
      width: pxToRem(100),
      textAlign: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_position_style: {
      width: pxToRem(150),
      textAlign: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_remark_style: {
      width: pxToRem(200),
      textAlign: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_update_time_style: {
      width: pxToRem(200),
      textAlign: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_acquirer_style: {
      width: pxToRem(200),
      textAlign: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_purpose_remark_style: {
      width: pxToRem(250),
      textAlign: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    platform_style: {
      width: pxToRem(150),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    phase_style: {
      width: pxToRem(90),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    target_style: {
      width: pxToRem(90),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    group_style: {
      width: pxToRem(130),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    cycle_style: {
      width: pxToRem(90),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    sku_style: {
      width: pxToRem(70),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    sn_style: {
      width: pxToRem(150),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    borrower_style: {
      width: pxToRem(100),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    status_style: {
      width: pxToRem(100),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    position_style: {
      width: pxToRem(150),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    remark_style: {
      width: pxToRem(200),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    update_time_style: {
      width: pxToRem(200),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    acquirer_style: {
      width: pxToRem(200),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    purpose_remark_style: {
      width: pxToRem(250),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
  };
});
