# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Default   # 本地 Agent Pool 名稱

steps:
- script: |
    cd django-react-soft-dashboard-main/react-ui
    npm install
    npm run build
  displayName: 'Build React'

- script: |
    sudo rm -rf /var/www/html/*
    sudo cp -r django-react-soft-dashboard-main/react-ui/build/* /var/www/html/
    sudo systemctl restart nginx
  displayName: 'Deploy to nginx'


