import { makeStyles } from "@mui/styles";

export default makeStyles(({ boxShadows, functions, borders, typography }) => {
  const { navbarBoxShadow } = boxShadows;
  const { rgba, pxToRem } = functions;
  const { borderRadius, borderWidth } = borders;
  const { size } = typography;
  return {
    title_table_row_style: {
      display: "flex",
      justifyContent: "space-between",
      width: "100%",
      textAlign: "center",
      // border: "1px solid black",
      padding: "0 1rem",
      backgroundColor: "#f5f5f5",
    },
    table_row_style: {
      display: "flex",
      justifyContent: "space-between",
      width: "100%",
      textAlign: "center",
      padding: "0 1rem",
      transition: "background-color 0.1s ease",
      "&:hover": {
        backgroundColor: "#f5f5f5",
      },
    },
    borderedOptionStyle: {
      border: "1px solid #000",
      padding: "3px",
      margin: "4px",
      maxWidth: "500px",
    },
    containerStyle: {
      display: "flex",
    },
    leftBlockStyle: {
      maxWidth: "400px",
      minWidth: "400px",
      flex: "0 0 400px", //flex-grow(區域優先級)、flex-shrink(區域空間不夠縮放優先級)、flex-basis
      marginRight: "10px",
      padding: "10px",
      background: "#efefef",
    },
    rightBlockStyle: {
      flex: "1",
      padding: "10px",
      background: "#f5f5f5",
    },
    line_form_style: {
      display: "flex",
      alignItems: "center",
      marginBottom: "14px",
      color: "#000000",
      fontSize: "18px",
    },
    customStyles: {
      content: {
        maxWidth: "1000px",
        minWidth: "1000px",
        maxHeight: "800px",
        minHeight: "800px",
        top: "50%",
        left: "50%",
        right: "auto",
        bottom: "auto",
        marginRight: "-500px",
        transform: "translate(-50%, -50%)",
        overflowY: "auto",
      },
      overlay: {
        zIndex: 9999,
      },
    },
    title_checkbox_style: {
      width: pxToRem(10),
      textAlign: "center",
      fontSize: pxToRem(16),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    title_platform_style: {
      width: pxToRem(180),
      textAlign: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_phase_style: {
      width: pxToRem(90),
      textAlign: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_target_style: {
      width: pxToRem(90),
      textAlign: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_group_style: {
      width: pxToRem(130),
      textAlign: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_cycle_style: {
      width: pxToRem(90),
      textAlign: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_sku_style: {
      width: pxToRem(70),
      textAlign: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_sn_style: {
      width: pxToRem(150),
      textAlign: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_borrower_style: {
      width: pxToRem(150),
      textAlign: "center",
      fontSize: pxToRem(16),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_status_style: {
      width: pxToRem(100),
      textAlign: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_position_style: {
      width: pxToRem(140),
      textAlign: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_remark_style: {
      width: pxToRem(180),
      textAlign: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_update_time_style: {
      width: pxToRem(200),
      textAlign: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    checkbox_style: {
      width: pxToRem(10),
      textAlign: "center",
      fontSize: pxToRem(16),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    platform_style: {
      width: pxToRem(180),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    phase_style: {
      width: pxToRem(90),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    target_style: {
      width: pxToRem(90),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    group_style: {
      width: pxToRem(130),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    cycle_style: {
      width: pxToRem(90),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    sku_style: {
      width: pxToRem(70),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    sn_style: {
      width: pxToRem(150),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    borrower_style: {
      width: pxToRem(150),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    status_style: {
      width: pxToRem(100),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    position_style: {
      width: pxToRem(140),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    remark_style: {
      width: pxToRem(180),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    update_time_style: {
      width: pxToRem(200),
      textAlign: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    // button_style: {
    //   display: "flex",
    //   width: "100px",
    //   padding: "5px 10px",
    //   transform: "rotate(0deg)",
    //   whiteSpace: "nowrap",
    //   backgroundColor: "#007bff",
    //   color: "#fff",
    //   border: "none",
    //   borderRadius: "5px",
    //   cursor: "pointer",
    //   fontSize: "14px",
    //   fontWeight: "bold",
    //   outline: "none",
    // },
    deleteButtonStyle: {
      cursor: "pointer",
      padding: "5px",
      backgroundColor: "lightcoral",
      border: "none",
      color: "white",
      minHeight: "35px",
      maxHeight: "35px",
    },
    iur_UI_delete: {
      cursor: "pointer",
      padding: "5px",
      backgroundColor: "#FA8072",
      border: "none",
      color: "white",
      position: "absolute",
      right: "15px",
    },
    filter_display: {
      maxWidth: "600px",
      maxHeight: "115px",
      overflowY: "auto",
    },
    add_new_machine: {
      display: "flex",
      alignItems: "center",
      backgroundColor: "#d32f2f", // 按钮背景色，深红色
      color: "#fff", // 按钮文字颜色，白色
      border: "none", // 移除按钮边框
      borderRadius: "4px", // 按钮圆角
      padding: "8px 16px", // 按钮内边距
      boxShadow: "none",
      "&:hover": {
        backgroundColor: "#b71c1c", // 按钮悬停背景色，深红色
        color: "#fff", // 按钮悬停文字颜色，白色
        boxShadow: "none",
      },
      minHeight: "30px",
    },
    downloadicon: {
      marginLeft: "8px",
    },
    addicon: {
      marginRight: "8px",
    },
    sn_scroll_container: {
      maxHeight: "140px",
      overflowY: "auto",
      overflowX: "hidden",
      borderRadius: "4px",
    },
    choose_container: {
      display: "flex",
      position: "relative",
      flexDirection: "column",
      maxHeight: "400px",
      minHeight: "200px",
      overflowY: "auto",
      overflowX: "hidden",
      borderRadius: "4px",
      backgroundColor: "#f0f0f0",
      fontFamily: "Calibri, sans-serif",
      fontWeight: "bold",
      padding: "10px",
    },
    file_add_button: {
      position: "absolute",
      bottom: "0px",
      right: "0px",
    },
    choose_view_container: {
      display: "flex",
      position: "relative",
      flexDirection: "column",
      maxHeight: "400px",
      minHeight: "400px",
      overflowY: "auto",
      overflowX: "hidden",
      borderRadius: "4px",
      backgroundColor: "#dcdcdc",
      fontFamily: "Calibri, sans-serif",
      fontWeight: "bold",
      padding: "10px",
      gap: "10px",
    },
    delete_button: {
      position: "absolute",
      cursor: "pointer",
      padding: "8px",
      backgroundColor: "lightcoral",
      border: "none",
      color: "white",
      right: "3px",
    },
    row: {
      display: "flex",
      flexDirection: "row",
      "&:hover": {
        backgroundColor: "#c0c0c0",
      },
    },
    fileUploadButton: {
      cursor: "pointer",
      padding: "5px 20px",
      backgroundColor: "#00aaff",
      color: "#fff",
      border: "none",
      borderRadius: "4px",
      textAlign: "center",
      display: "inline-block",
      fontSize: "16px",
      fontWeight: "bold",
      userSelect: "none",
      transition: "background-color 0.3s ease",
      lineHeight: "25px",
      "&:hover": {
        backgroundColor: "#0088cc",
      },
      "&:active": {
        backgroundColor: "#0077bb",
      },
      "&:focus": {
        outline: "none",
      },
    },
    select: {
      minHeight: "30px",
      padding: "2px 20px",
      marginLeft: "10px",
      borderRadius: "50px",
      border: "1px solid #ccc",
      outline: "none",
      fontSize: "14px",
      alignItems: "center",
    },
    width_search: {
      minHeight: "30px",
      padding: "2px 20px",
      marginLeft: "10px",
      borderRadius: "50px",
      border: "1px solid #ccc",
      outline: "none",
      fontSize: "14px",
    },
    title_bottom: {
      display: "flex",
      flexDirection: "row",
      marginBottom: "10px",
      alignItems: "center",
    },
    title_right: {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      position: "absolute",
      right: "10px",
      gap: "5px",
    },
    test: {
      display: "flex",
      justifyContent: "space-between",
      width: "100%",
      textAlign: "center",
      boxShadow: navbarBoxShadow,
      color: rgba(0, 0, 0, 0.5),
      fontSize: pxToRem(size),
      borderRadius: borderRadius,
      borderWidth: borderWidth,
    },
  };
});
