import { makeStyles } from "@mui/styles";

export default makeStyles(({ boxShadows, functions, borders, typography }) => {
  const { navbarBoxShadow } = boxShadows;
  const { rgba, pxToRem } = functions;
  const { borderRadius, borderWidth } = borders;
  const { size } = typography;
  return {
    line_form_style: {
      display: "flex !important",
      alignItems: "center !important",
      marginBottom: "14px !important",
      marginTop: "30px", // 與上方保持距離
      gap: "10px", // 設置 Remove Category 和 Category Name 的水平間距
      color: "#000000 !important",
      fontSize: "18px !important",
    },

    columns_center: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
    },
    disabled: {
      pointerEvents: "none",
      backgroundColor: "#f0f0f0",
      color: "#a0a0a0",
      opacity: 0.6,
    },
    hint_word: {
      fontSize: "0.8rem",
      color: "#FF0000",
    },
    create_title_table_row_style: {
      display: "grid",
      justifyContent: "space-between",
      width: "100%",
      textAlign: "center",
      gridTemplateColumns: "repeat(4, 1fr)", // 輸入框 4 等分
      backgroundColor: "#f5f5f5",
    },
    title_table_row_style: {
      display: "flex",
      justifyContent: "space-between",
      width: "100%",
      textAlign: "center",
      padding: "0 1rem",
      backgroundColor: "#f5f5f5",
    },
    create_plan_name: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      fontWeight: 900,
      color: "#333333",
    },
    plan_type: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      fontWeight: 900,
      color: "#333333",
      borderBottom: "none", // 移除下劃線
    },
    editor: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      fontWeight: 900,
      color: "#333333",
      borderBottom: "none", // 移除下劃線
    },
    reviewer: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      fontWeight: 900,
      color: "#333333",
      borderBottom: "none", // 移除下劃線
    },
    table_row_style: {
      display: "flex",
      justifyContent: "space-between",
      width: "100%",
      textAlign: "center",
      padding: "0 1rem",
      transition: "background-color 0.1s ease",
      "&:hover": {
        backgroundColor: "#f5f5f5",
      },
    },
    input_table_row_style: {
      textAlign: "center",
      display: "grid",
      gridTemplateColumns: "repeat(4, 1fr)", // 輸入框 4 等分
      gap: "16px",
      width: "100%",
      padding: "12px 16px",
    },

    test_case_category: {
      fontSize: pxToRem(17),
      color: "#333333",
      padding: "8px 0",
      display: "block",
      textAlign: "left",
      marginBottom: "8px",
      fontWeight: "normal",
    },

    // title_no: {
    //   flex: 1,
    //   display: "flex",
    //   alignItems: "center",
    //   justifyContent: "center",
    //   fontSize: pxToRem(17),
    //   wordWrap: "break-word",
    //   borderBottom: "none !important",
    //   fontWeight: 900,
    //   color: "#333333",
    // },
    title_plan_name: {
      flex: 3,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_type: {
      flex: 2, // 比例分配，占比 2
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_update_time: {
      flex: 2, // 比例分配，占比 2
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_action: {
      flex: 2, // 比例分配，占比 2
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },

    // no: {
    //   flex: 1, // 比例分配，占比 0.5
    //   display: "flex",
    //   alignItems: "center",
    //   justifyContent: "center",
    //   fontSize: pxToRem(14),
    //   wordWrap: "break-word",
    //   borderBottom: "none !important",
    //   fontWeight: 900,
    //   color: "#333333",
    // },
    plan_name: {
      flex: 3, // 比例分配，占比 3
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    type: {
      flex: 2, // 比例分配，占比 2
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },

    action: {
      flex: 2, // 比例分配，占比 2
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    edit_title_plan_name: {
      flex: 2,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      fontWeight: 900,
      color: "#333333",
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    edit_title_type: {
      flex: 2,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      fontWeight: 900,
      color: "#333333",
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    edit_title_version: {
      flex: 1,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      fontWeight: 900,
      color: "#333333",
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    edit_title_last_editor: {
      flex: 2,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      fontWeight: 900,
      color: "#333333",
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    edit_title_update_time: {
      flex: 2,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      fontWeight: 900,
      color: "#333333",
      wordWrap: "break-word",
      borderBottom: "none !important",
    },

    edit_plan_name: {
      flex: 2,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      fontWeight: 400,
      color: "#333333",
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    edit_type: {
      flex: 2,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      fontWeight: 400,
      color: "#333333",
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    edit_version: {
      flex: 1,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      fontWeight: 400,
      color: "#333333",
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    edit_last_editor: {
      flex: 2,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      fontWeight: 400,
      color: "#333333",
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    edit_update_time: {
      flex: 2,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      fontWeight: 400,
      color: "#333333",
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    view_title_plan_name: {
      flex: 2,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontWeight: 900,
      borderBottom: "none",
    },
    view_title_type: {
      flex: 2,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontWeight: 900,
      borderBottom: "none",
    },
    view_title_version: {
      flex: 0.8,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontWeight: 900,
      borderBottom: "none",
    },
    view_title_last_editor: {
      flex: 2,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontWeight: 900,
      borderBottom: "none",
    },
    view_title_update_time: {
      flex: 2,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontWeight: 900,
      borderBottom: "none",
    },
    view_title_editors: {
      flex: 1.5,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontWeight: 900,
      borderBottom: "none",
    },
    view_title_reviewers: {
      flex: 1.5,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontWeight: 900,
      borderBottom: "none",
    },
    list_plan_name: {
      flex: 2,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontWeight: 400,
      borderBottom: "none",
    },
    list_type: {
      flex: 2,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontWeight: 400,
      borderBottom: "none",
    },
    list_version: {
      flex: 0.8,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontWeight: 400,
      borderBottom: "none",
    },
    last_editor: {
      flex: 2,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontWeight: 400,
      borderBottom: "none",
    },
    update_time: {
      flex: 2,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontWeight: 400,
      borderBottom: "none !important",
    },
    editors: {
      flex: 1.5,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontWeight: 400,
      borderBottom: "none",
    },
    reviewers: {
      flex: 1.5,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontWeight: 400,
      borderBottom: "none",
    },

    search: {
      width: pxToRem(300),
      fontSize: pxToRem(14),
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    test: {
      display: "flex",
      justifyContent: "space-between",
      width: "100%",
      textAlign: "center",
      boxShadow: navbarBoxShadow,
      color: rgba(0, 0, 0, 0.5),
      fontSize: pxToRem(size),
      borderRadius: borderRadius,
      borderWidth: borderWidth,
    },
    tooltip: {
      backgroundColor: "rgba(0, 0, 0, 0.87)",
      color: "#fff",
      fontSize: pxToRem(14),
      border: `1px solid ${rgba(255, 255, 255, 0.2)}`,
      padding: "10px",
      borderRadius: pxToRem(8),
      boxShadow: navbarBoxShadow,
      maxWidth: "300px",
    },
    tooltipArrow: {
      color: "rgba(0, 0, 0, 0.87)",
    },

    test_case_table: {
      display: "grid",
      gridTemplateColumns: "5% 20% 35% 35% 5%",
      width: "100%",
      alignItems: "center",
      textAlign: "center",
    },

    test_case_header: {
      fontWeight: "bold",
      fontSize: "1rem",
      padding: "8px",
      textAlign: "center",
      width: "100%",
      gridTemplateColumns: "5% 20% 35% 35% 5%",
      backgroundColor: "#f5f5f5",
    },

    test_case_cell: {
      fontSize: "0.9rem",
      padding: "8px",
      textAlign: "center",
      overflow: "hidden",
      textOverflow: "ellipsis",
      gridTemplateColumns: "5% 20% 35% 35% 5%",
      wordWrap: "break-word",
      borderBottom: "none",
    },
    test_case_label: {
      marginLeft: "75px",
      marginRight: "10px",
      color: "#333333",
    },
    // Editor and Reviewer styles
    editorsReviewersContainer: {
      display: "flex",
      flexDirection: "column",
      maxHeight: "100px",
      overflowY: "auto",
      overflowX: "hidden",
      padding: "10px",
      border: `${pxToRem(1)} solid ${rgba(0, 0, 0, 0.2)}`,
      borderRadius: borderRadius.md,
      boxShadow: navbarBoxShadow,
      backgroundColor: "#ffffff",
      fontSize: size.sm,
    },

    inlineList: {
      display: "flex",
      flexWrap: "wrap",
      padding: 0,
      margin: 0,
      listStyleType: "none",
    },

    inlineListItem: {
      marginRight: pxToRem(10),
      marginBottom: pxToRem(5),
      whiteSpace: "nowrap",
      color: "#000000",
      fontSize: size.sm,
    },

    editorsReviewersTitle: {
      marginBottom: pxToRem(10),
      fontSize: size.md,
      fontWeight: "bold",
      color: rgba(0, 0, 0, 0.8),
    },
  };
});
