import { makeStyles } from "@mui/styles";

export default makeStyles(({ boxShadows, functions, borders, typography }) => {
  const { navbarBoxShadow } = boxShadows;
  const { rgba, pxToRem } = functions;
  const { borderRadius, borderWidth } = borders;
  const { size } = typography;
  return {
    line_form_style: {
      display: "flex",
      alignItems: "center",
      marginBottom: "14px",
      color: "#000000",
      fontSize: "18px",
    },
    columns_center: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
    },
    disabled: {
      pointerEvents: "none",
      backgroundColor: "#f0f0f0",
      color: "#a0a0a0",
      opacity: 0.6,
    },
    hint_word: {
      fontSize: "0.8rem",
      color: "#FF0000",
    },
    title_table_row_style: {
      display: "flex",
      justifyContent: "space-between",
      width: "100%",
      textAlign: "center",
      padding: "0 1rem",
      backgroundColor: "#f5f5f5",
    },
    table_row_style: {
      display: "flex",
      justifyContent: "space-between",
      width: "100%",
      textAlign: "center",
      padding: "0 1rem",
      transition: "background-color 0.1s ease",
      "&:hover": {
        backgroundColor: "#f5f5f5",
      },
    },
    title_case_name: {
      maxWidth: pxToRem(180),
      minWidth: pxToRem(180),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_description: {
      maxWidth: pxToRem(600),
      minWidth: pxToRem(600),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_tag: {
      width: pxToRem(180),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_action: {
      width: pxToRem(180),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    case_name: {
      maxWidth: pxToRem(180),
      minWidth: pxToRem(180),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    description: {
      maxWidth: pxToRem(600),
      minWidth: pxToRem(600),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(12),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    tag: {
      width: pxToRem(180),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    action: {
      width: pxToRem(180),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    test: {
      display: "flex",
      justifyContent: "space-between",
      width: "100%",
      textAlign: "center",
      boxShadow: navbarBoxShadow,
      color: rgba(0, 0, 0, 0.5),
      fontSize: pxToRem(size),
      borderRadius: borderRadius,
      borderWidth: borderWidth,
    },
  };
});
