import { makeStyles } from "@mui/styles";

export default makeStyles(({ functions }) => {
  const { pxToRem } = functions;
  return {
    title_table_row_style: {
      display: "flex",
      justifyContent: "space-between",
      width: "100%",
      textAlign: "center",
      padding: "0 1rem",
      backgroundColor: "#f5f5f5",
    },
    table_row_style: {
      display: "flex",
      justifyContent: "space-between",
      width: "100%",
      textAlign: "center",
      padding: "0 1rem",
      transition: "background-color 0.1s ease",
      "&:hover": {
        backgroundColor: "#f5f5f5",
      },
    },
    title_email: {
      maxWidth: pxToRem(180),
      minWidth: pxToRem(180),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_appid: {
      maxWidth: pxToRem(120),
      minWidth: pxToRem(120),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_secret: {
      maxWidth: pxToRem(180),
      minWidth: pxToRem(180),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_approve: {
      maxWidth: pxToRem(600),
      minWidth: pxToRem(600),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    title_signin: {
      maxWidth: pxToRem(160),
      minWidth: pxToRem(160),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(17),
      wordWrap: "break-word",
      borderBottom: "none !important",
      fontWeight: 900,
      color: "#333333",
    },
    email: {
      maxWidth: pxToRem(180),
      minWidth: pxToRem(180),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(14),
      wordWrap: "break-word",
      borderBottom: "none !important",
    },
    appid: {
      maxWidth: pxToRem(120),
      minWidth: pxToRem(120),
      display: "flex",
      alignItems: "center",
      justifyContent: "flex-start",
      fontSize: pxToRem(12),
      wordWrap: "break-word",
      borderBottom: "none !important",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    secret: {
      maxWidth: pxToRem(180),
      minWidth: pxToRem(180),
      display: "flex",
      alignItems: "center",
      justifyContent: "flex-start",
      fontSize: pxToRem(12),
      wordWrap: "break-word",
      borderBottom: "none !important",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    approve: {
      maxWidth: pxToRem(600),
      minWidth: pxToRem(600),
      display: "flex",
      alignItems: "center",
      justifyContent: "flex-start",
      fontSize: pxToRem(12),
      wordWrap: "break-word",
      borderBottom: "none !important",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    signin: {
      maxWidth: pxToRem(120),
      minWidth: pxToRem(120),
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: pxToRem(12),
      wordWrap: "break-word",
      borderBottom: "none !important",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    borderedOptionStyle: {
      border: "1px solid #000",
      padding: "3px",
      margin: "4px",
      maxWidth: "500px",
    },
    containerStyle: {
      display: "flex",
    },
    leftBlockStyle: {
      maxWidth: "400px",
      minWidth: "400px",
      flex: "0 0 400px", //flex-grow(區域優先級)、flex-shrink(區域空間不夠縮放優先級)、flex-basis
      marginRight: "10px",
      padding: "10px",
      background: "#efefef",
    },
    textField: {
      width: "100%",
      padding: "10px",
      fontSize: "16px",
      border: "1px solid #ccc",
      borderRadius: "5px",
      boxSizing: "border-box",
    },
    eyeIcon: {
      position: "absolute",
      top: "50%",
      right: "10px",
      transform: "translateY(-50%)",
    },
    rightBlockStyle: {
      flex: "1",
      padding: "10px",
      background: "#f5f5f5",
    },
    line_form_style: {
      display: "flex",
      alignItems: "center",
      marginBottom: "14px",
      color: "#000000",
      fontSize: "18px",
    },
    customStyles: {
      content: {
        maxWidth: "1000px",
        minWidth: "1000px",
        maxHeight: "800px",
        minHeight: "800px",
        top: "50%",
        left: "50%",
        right: "auto",
        bottom: "auto",
        marginRight: "-500px",
        transform: "translate(-50%, -50%)",
        overflowY: "auto",
      },
      overlay: {
        zIndex: 9999,
      },
    },
    button_style: {
      display: "flex",
      width: "100px",
      padding: "5px 10px",
      transform: "rotate(0deg)",
      whiteSpace: "nowrap",
      backgroundColor: "#007bff",
      color: "#fff",
      border: "none",
      borderRadius: "5px",
      cursor: "pointer",
      fontSize: "14px",
      fontWeight: "bold",
      outline: "none",
    },
    deleteButtonStyle: {
      cursor: "pointer",
      padding: "5px",
      backgroundColor: "lightcoral",
      border: "none",
      color: "white",
    },
    iur_UI_delete: {
      cursor: "pointer",
      padding: "5px",
      backgroundColor: "#FA8072",
      border: "none",
      color: "white",
      position: "absolute",
      right: "15px",
    },
    filter_display: {
      maxWidth: "600px",
      maxHeight: "115px",
      overflowY: "auto",
    },
  };
});
